### ISSUE TITLE
[Feature] V2 서버 헬스체크 구현

### ISSUE THREAD

**Issue by jjj5306** [NginxXServer/NginxX-ProxyServer#6]
## 기능 설명 📘

 **리버스 프록시 서버에서 패시브 헬스체크**
    - 실제 요청/응답을 통해 서버의 상태를 파악함. 모든 요청은 리버스 프록시 서버를 거치므로 별도의 상태 확인 요청이 필요하지 않음.
    - HTTP 서버의 CPU, 메모리 상태 등은 체크할 수 없지만 HTTP 서버를 수정하지 않아도 되고, 불필요한 트래픽이 발생하지 않는다는 점에서 가장 적합하다고 판단.

<br>

### 작동 방식

1. 클라이언트 요청 수신
2. 리버스 프록시 요청 처리 및 모니터링
    - 현재 처리중인 요청 수 증가
    - 요청 시작 시간 기록
    - HTTP 서버 선택
3. HTTP 서버로 요청 전달
4. 응답 처리
    - 처리중인 요청 수 감소
    - 응답 시간 계산
    - 성공/실패 여부 기록
    - 서버 상태 업데이트
5. 클라이언트에 응답 전달

### Task List
- [ ]  서버 상태 모니터링 구조 구현
- [ ]  로그 시스템 개선
- [ ]  메트릭 수집 및 관리
    - [ ]  서버별 메트릭 : 현재 활성 요청 수, 총 처리 요청 수, 평균 응답 시간, 실패율
    - [ ]  전체 시스템 메트릭 : 총 처리량, 전체 에러율, 부하 분산 상태
